apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-test
spec:
  selector:
    matchLabels:
      app: minikube-test
  replicas: 2
  template:
    metadata:
      labels:
        app: minikube-test
    spec:
      containers:
      - name: minikube-test
        image: local/minikube-test:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minikube-test
spec:
  selector:
    app: minikube-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

