apiVersion: v1
kind: Service
metadata:
  name: minikube-test
spec:
  selector:
    app: minikube-test   # Match the label defined in the deployment.yaml file
  ports:
    - protocol: TCP
      port: 80             # Expose port 80 from the service
      targetPort: 80       # Forward traffic to port 80 on the container
  type: NodePort           # Expose the service to the outside world
