name: Minikube CI Test

on:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Cluster Check
        run: kubectl get nodes

      - name: Build Docker Image in Minikube
        run: minikube image build -t local/minikube-test:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl wait --for=condition=ready pod -l app=minikube-test --timeout=90s

      - name: Access service via curl
        run: |
          echo "Service URL:"
          minikube service minikube-test --url
          curl $(minikube service minikube-test --url)
