name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build example and deploy to Minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: medyagh/local-dev-example-with-minikube
    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: "latest"  # Ensuring we use the latest version of Minikube
    - name: Start Minikube Cluster
      run: |
        minikube start --driver=docker  # Make sure Minikube starts correctly
    - name: Verify Minikube Cluster
      run: kubectl get nodes  # Verify that the nodes are up and running
    - name: Build Docker Image
      run: |
        eval $(minikube -p minikube docker-env)  # Set Docker environment for Minikube
        docker build -t local/minikube-test:latest .  # Build the Docker image inside Minikube's Docker daemon
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
    - name: Wait for Pods to be Ready
      run: |
        kubectl wait --for=condition=ready pod -l app=minikube-test --timeout=300s
    - name: Get Pod Logs (for debugging)
      run: |
        kubectl logs -l app=minikube-test
    - name: Test service URLs
      run: |
        minikube service list  # List all services in Minikube
        SERVICE_URL=$(minikube service minikube-test --url)  # Get the URL of your service
        echo "Service URL: $SERVICE_URL"
        curl $SERVICE_URL  # Test the service by making a request

